# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: DemoApp
    type: github
    endpoint: mgunukula
    name: mgunukula/DemoApp

  - repository: ScheduledJobs
    type: github
    endpoint: mgunukula
    name: mgunukula/ScheduledJobs

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: DemoApp
- checkout: ScheduledJobs

- script: dir $(Build.SourcesDirectory)
    
